webportfolio/apps/blog/urls.py
from django.urls import path
from .views import render_post, post_detail

app_name = 'blog'

urlpatterns = [ path("", render_post, name='posts'),
                path('<int:post_id>', post_detail, name='post_detail'),
                ]

webportfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from webportfolio.apps.portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/',include('webportfolio.apps.blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webportfolio/apps/blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images/')
    date = models.DateField(datetime.date.today)

webportfolio/apps/portfolio/models.py
from django.db import models

class Portfolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

webportfolio/apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_post(request):
    posts = Post.objects.all()
    return render(request, 'post.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request,'detail.html',{'post':post})

webportfolio/apps/portfolio/views.py
from django.shortcuts import render
from .models import Portfolio

def home(request):
    projects = Portfolio.objects.all()
    return render(request, 'home.html', {'projects' : projects})

webportfolio/apps/blog/templates/detail.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
<div class="text-center mb-4">
<h2 class="post-title">{{post.title}}</h2>
    <h3 class="post-date">
        <i class="fas fa-calendar-alt"></i> {{post.date|date:'M d y'}}</h3>
</div>
    <div class="post-image text-center mb-4">
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid rounded shadow-lg">
    </div>
<div class="post-description text-justify px-md-5">
    <p class="text-muted">{{ post.description}}</p>
</div>
</div>

{% endblock %}

webportfolio/apps/blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}

    <h1 class="text-center text-dark mb-4">Posts</h1>
{% for post in posts %}
<div class="p-3">
    <div class="card card-body bg-black">
<div class="row">
    <div class="col-3">
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
    </div>
    <div class="col-9">
        <h1>{{post.title}}</h1>
    <h2>{{post.date|date:"M d Y"}}</h2>
    <p>{{post.description|striptags|truncatechars:200|safe}}</p>
        <a href="{% url 'blog:post_detail' post.id%}" class="btn btn-primary">{{post.title}}</a>
    </div>
</div>

</div>
</div>
{% endfor %}
{% endblock %}

webportfolio/apps/portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
<header class="header row bg-white shadow-md p-6 rounded-lg">
    <div class="header-content col-md-4 text-center">
        <img src="{% staticfiles 'portfolio/profile.jpg' %}" alt="Profile image" class="img-fluid rounded-circle mb-3">
    </div>
    <div class="col-md-8 my auto">
        <h1 class="text-dark mb-3">Hi, I'm <strong>Eber Josue</strong></h1>
        <h3 class=" h3 text-secondary mb-4">Im a System Engineer and Web Developer</h3>
        <p class="text-muted mt-3">
            I am a Systems Engineering student with a passion for technology, problem-solving, and innovation. Currently pursuing my degree, I have been involved in projects like LogicTrack, where I contributed to implementing practical solutions with real-life applications. This experience has strengthened my skills in programming, software development, and system design, and I am eager to apply my knowledge to tackle real-world challenges and grow in a dynamic, fast-paced environment
        </p>
        <a href="{% staticfiles 'portfolio/CV.pdf' %}" class="btn btn-primary mt-3"
        >Download CV</a>
    </div>
</header>
<div class="row my-4 text-center">
    <h1 class="text-dark">My projects</h1>
    <p class="text-muted">Here are some of the projects I've worked on:</p>
    {% for project in projects %}
<div class="col-md-4 p-4">
    <div class="card  card-project">
        <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
        <div class="card-body">

            <h2 class="text-dark">{{project.title}}</h2>
            <p class="text-muted">{{project.description}}</p>
{% if project.url %}
<a href="{{project.url}}" class="btn btn-outline-primary btn-sm" target="_blank">View project</a>
{% endif %}
        </div>
    </div>
</div>
{% endfor %}
    </div>
<button class="scroll-top" onclick="window.scrollTo({ top: 0, behavior: 'smooth' });">
    <i class="fas fa-chevron-up"></i>
</button>
{% endblock %}

</div>

webportfolio/apps/portfolio/templates/layout.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% staticfiles 'main.css' %}">
</head>
<body class="text-light">
{% include 'parshas/navbar.html' %}
<div class="container p-4">
     {% block content %}
     {% endblock %}
</div>

</body>
</html>

webportfolio/apps/portfolio/templates/parshas/navbar.html
{% load static %}
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<nav class="navbar navbar-expand-lg bg-black py-3 shadow">
  <div class="container">
    <a class="navbar-brand text-white d-flex align-items-center" href="/">
      <i class="fas fa-home me-2"></i> Home
    </a>
    <button class="navbar-toggler text-white border-0" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item d-flex align-items-center">
          <a class="nav-link text-white d-flex align-items-center" href="{% url 'blog:posts' %}">
            <i class="fas fa-blog me-2"></i> Blog
          </a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm text-white" href="{% static 'portfolio/Cv.pdf' %}">
            <i class="fas fa-download me-1"></i> Download CV
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>